apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" .Release.Name | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "dander-control.labels" . | nindent 4 }}
data:
  control-oidc.json: {{ required "control.oidcConfig is required" .Values.control.oidcConfig | quote }}
  control-graph-store.json: {{ required "control.graphStoreConfig is required" .Values.control.graphStoreConfig | quote }}
  bootstrap.json: {{ required "druff.bootstrap is required" .Values.druff.bootstrap | quote }}
