apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-graph-store" .Release.Name | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "dander-control.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.graphStore.accessMode }}
  resources:
    requests:
      storage: {{ .Values.graphStore.size }}
