{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-runtime-read" .Release.Name | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "dander.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-runtime-read" .Release.Name | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "dander.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "dander.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ printf "%s-runtime-read" .Release.Name | trunc 63 | trimSuffix "-" }}
{{- end }}
